services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Nitsan\BlogSystem\:
    resource: '../Classes/*'

  Nitsan\BlogSystem\EventListener\CommentFilterationListener:
    tags:
      - name: event.listener
        identifier: 'comment-filteration'
        event: Nitsan\BlogSystem\Event\CommentFilterationEvent
  
  Nitsan\BlogSystem\EventListener\BeforeActionCallListener:
    tags:
      - name: event.listener
        identifier: 'blog-before-action'
        event: TYPO3\CMS\Extbase\Event\Mvc\BeforeActionCallEvent

